name: 'Test the Code'


env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

on: workflow_dispatch

jobs:

  tools:
    strategy:
      fail-fast: false
    name: 'Validate Terraform Docs'
    concurrency: 
      group: validate
      cancel-in-progress: false
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    defaults:
      run:
        shell: bash
        working-directory: ./
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform Install Check
      run: |
        cd /tmp
        apt-get update && apt-get install -y curl unzip
        echo "downloading terraform" && curl -sSLo ./terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_arm.zip
        echo "installing terraform" && unzip -u terraform.zip && rm terraform.zip && mv terraform /usr/local/bin/terraform
        echo "checking terraform" && terraform version
  
    - name: Terraform-docs installation
      run: |
        cd /tmp
        curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-arm.tar.gz
        tar -xzf terraform-docs.tar.gz && chmod +x terraform-docs && mv terraform-docs /usr/local/bin/terraform-docs
        aws s3 ls s3://terraform-training-tfstates/

    - name: Terraform Format
      run: terraform fmt -check -recursive
 